var stations = {
  val202: {image: "val202.png", name: "Val202", stream: "http://mp3.rtvslo.si/val202", vol: 0.8 },
  prvi: {image: "prvi.png", name: "Radio Prvi", stream: "http://mp3.rtvslo.si/ra1" },
  rsi: {image: "rsi.jpg", name: "Radio Slovenia", stream: "http://mp3.rtvslo.si/rsi" },
  koroskiradio: {name: "Koroški radio Slovenj Gradec", stream: "http://shoutcast.netsi.net:8300/;" },
  mojradio: {name: "Moj radio Velenje", stream: "http://stream.linit.si:8006/" },
  radio1: {name: "Radio 1", stream: "http://live.radio1.si/Radio1" },
  radio94: {name: "Radio 94", stream: "http://193.9.52.161:8443/radio94"},
  radioaktual: {name: "Radio Aktual", stream: "http://stream.radioaktual.si/Aktual", vol: 0.6 },
  radioantena: {name: "Radio Antena", stream: "http://live.radioantena.si/Antena" },
  radiobrezje: {name: "Radio Brezje", stream: "http://93.103.175.209:8000/;stream.mp3" },
  radiocapodistria: {name: "Radio Capodistria", stream: "http://mp3.rtvslo.si/capo" },
  radiocapris: {name: "Radio Capris", stream: "http://stream01.exit.si:8000/live" },
  radiocelje: {name: "Radio Celje", stream: "http://stream.rgl.si/Celje" },
  radiocenter: {name: "Radio Center", stream: "http://stream2.radiocenter.si:8000/center", vol: 0.6 },
  radiocity: {name: "Radio City", stream: "http://82.149.22.34:8000/CityMp3128.mp3" },
  // preimenuj v BOB
  radioeuropa: {name: "Radio Europa", stream: "http://live.radiobob.si/Europa05" },
  radioexpres: {name: "Radio Expres", stream: "http://stream2.radioekspres.si:8016/stream" },
  radiogorenc: {name: "Radio Gorenc", stream: "http://stream.radiogorenc.si:8000/radiogorenc.mp3", vol: 0.6 },
  radiohit: {name: "Radio Hit", stream: "http://stream03.exit.si:8000/radiohit" },
  radiokoper: {name: "Radio Koper", stream: "http://mp3.rtvslo.si/rakp" },
  radiokranj: {name: "Radio Kranj", stream: "http://live.radio-kranj.si/Kranj" },
  radiokrka: {name: "Radio Krka", stream: "https://live.radio.si/Krka" },
  radiolaser: {name: "Radio Laser", stream: "http://shoutcast.netsi.net:8100/;" },
  radiomaribor: {name: "Radio Maribor", stream: "http://mp3.rtvslo.si/ramb" },
  radiomars: {name: "Radio Marš", stream: "http://frekvenca.eu:8000/radiomars.mp3" },
  radiomaxi : {name: "Radio Maxi", stream: "https://live.radio.si/Maxi" },
  radiomurskival: {name: "Radio Murski val", stream: "http://webradio.murskival.si:8000/mv.mp3" },
  radionetfm: {name: "Radio Net FM", stream: "hhttp://reflector.radionet.si:8000/radionetlive.ogg" },
  radioognjisce: {name: "Radio Ognjišče", stream: "http://real.ognjisce.si:8000/ognjisce.mp3" },
// radiopotepuh.jpg
  radioprlek: {name: "Radio Prlek", stream: "http://89.212.242.158:8000/;" },
  radioptuj: {name: "Radio Ptuj", stream: "http://stream.radio-ptuj.si:8000/;" },
  radiorobin: {name: "Radio Robin", stream: "http://stream-dis.radio.si/Robin" },
  radiorogla: {name: "Radio Rogla", stream: "http://193.105.67.24:8010/" },
  radiosalomon: {name: "Radio Salomon", stream: "http://84.52.138.44/Salomon" },
  radios: {name: "Radio S", stream: "http://live.radio.si/radios" },
  radioslovenske: {name: "Radio Slovenske gorice", stream: "http://46.105.43.31:8050/stream/1/" },
  radiosora: {name: "Radio Sora", stream: "http://radio-sora.si:8000/radio-sora.mp3" },
  radiosraka: {name: "Radio Sraka", stream: "http://193.105.67.24:8006/" },
  radiostudent: {name: "Radio Študent", stream: "http://kruljo.radiostudent.si:8000/hiq" },
  radiotop: {name: "Radio Top", stream: "http://193.105.67.24:8024/" },
  radiotriglav: {name: "Radio Triglav", stream: "http://live.radiotriglav.si/Triglav" },
  radioveseljak: {name: "Radio Veseljak", stream: "http://84.52.138.44/Veseljak" },
  radiovelenje: {name: "Radio Velenje", stream: "http://212.18.39.42:8000/radiovelenje.mp3", vol: 0.8 },
  radiozelenival: {name: "Radio Zeleni val", stream: "https://jurepeterka.radioca.st/;" },
  rockradio: {name: "Rock radio", stream: "http://stream.rockradio.si:9034/;" },

};