var stations = {
  val202: {image: "val202.png", name: "Val202", stream: "https://mp3.rtvslo.si/val202", vol: 0.8 },
  prvi: {image: "prvi.png", name: "Radio Prvi", stream: "https://mp3.rtvslo.si/ra1" },
  rsi: {image: "rsi.jpg", name: "Radio Slovenia", stream: "https://mp3.rtvslo.si/rsi" },
  koroskiradio: {name: "Koroški radio Slovenj Gradec", stream: "https://live.radio.si/Koroski" },
  mojradio: {name: "Moj radio Velenje", stream: "https://stream.mojradio.si:8000/mojradio" },
  radio1: {name: "Radio 1", stream: "https://live.radio1.si/Radio1" },
  radio94: {name: "Radio 94", stream: "http://77.38.12.198:8000/radio94"},
  radioaktual: {name: "Radio Aktual", stream: "https://live.radio.si/Aktual", vol: 0.6 },
  radioantena: {name: "Radio Antena", stream: "http://live.radioantena.si/Antena" },
  radiobrezje: {name: "Radio Brezje", /*stream: "http://93.103.175.209:8000/;stream.mp3"*/ },
  radiocapodistria: {name: "Radio Capodistria", stream: "https://mp3.rtvslo.si/capo" },
  radiocapris: {name: "Radio Capris", stream: "https://stream.exit.si/live", vol: 0.7 },
  radiocelje: {name: "Radio Celje", stream: "https://live.radio.si/Celje" },
  radiocenter: {name: "Radio Center", stream: "http://stream2.radiocenter.si:8000/center", vol: 0.6 },
  radiocity: {name: "Radio City", stream: "https://stream1.radiocity.si/CityMp3128.mp3" },
  // preimenuj v BOB
  radioeuropa: {name: "Radio Europa", stream: "http://live.radiobob.si/Europa05" },
  radioekspres: {name: "Radio Ekspres", stream: "https://stream.nextmedia.si/proxy/ekspres2?mp=/stream" },
  radiogorenc: {name: "Radio Gorenc", stream: "https://stream.radiogorenc.si:8001/radiogorenc.mp3", vol: 0.6 },
  radiohit: {name: "Radio Hit", stream: "http://stream03.exit.si:8000/radiohit" },
  radiokoper: {name: "Radio Koper", stream: "https://mp3.rtvslo.si/rakp" },
  radiokranj: {name: "Radio Kranj", stream: "http://live.radio-kranj.si/Kranj" },
  radiokrka: {name: "Radio Krka", stream: "https://live.radio.si/Krka" },
  radiolaser: {name: "Radio Laser", /*stream: "http://shoutcast.netsi.net:8100/;"*/ },
  radiomaribor: {name: "Radio Maribor", stream: "https://mp3.rtvslo.si/rmb" },
  radiomars: {name: "Radio Marš", stream: "http://frekvenca.eu:8000/radiomars.mp3" },
  radiomaxi : {name: "Radio Maxi", stream: "https://live.radio.si/Maxi" },
  radiomurskival: {name: "Radio Murski val", stream: "http://webradio.murskival.si:8000/mv.mp3" },
  radionetfm: {name: "Radio Net FM", stream: "http://reflector.radionet.si:8000/radionetlive.ogg" },
  radioognjisce: {name: "Radio Ognjišče", stream: "http://real.ognjisce.si:8000/ognjisce.mp3" },
// radiopotepuh.jpg
  radioprlek: {name: "Radio Prlek", stream: "http://86.61.68.81:8000/;stream.nsv&type=mp3" },
  radioptuj: {name: "Radio Ptuj", stream: "https://live.radio.si/Ptuj" },
  radiorobin: {name: "Radio Robin", stream: "https://live.radio.si/Robin" },
  radiorogla: {name: "Radio Rogla", stream: "https://rogla.siradiostream.net/;" },
  radiosalomon: {name: "Radio Salomon", stream: "http://84.52.138.44/Salomon" },
  radios: {name: "Radio S", stream: "http://live.radio.si/radios" },
  radioslovenske: {name: "Radio Slovenske gorice", stream: "https://stream.iradio.pro/proxy/radioslovenskegoric?mp=/stream" },
  radiosora: {name: "Radio Sora", stream: "http://radio-sora.si:8000/radio-sora.mp3" },
  radiosraka: {name: "Radio Sraka", stream: "http://193.105.67.24:8006/" },
  radiostudent: {name: "Radio Študent", stream: "http://kruljo.radiostudent.si:8000/hiq" },
  radiotop: {name: "Radio Top", /*stream: "http://193.105.67.24:8024/"*/ },
  radiotriglav: {name: "Radio Triglav", stream: "http://live.radiotriglav.si/Triglav" },
  radioveseljak: {name: "Radio Veseljak", stream: "https://live.radio.si/Veseljak" },
  radiovelenje: {name: "Radio Velenje", stream: "https://live.radio.si/Velenje", vol: 0.8 },
  radiozelenival: {name: "Radio Zeleni val", stream: "https://jurepeterka.radioca.st/;" },
  rockradio: {name: "Rock radio", stream: "http://stream.rockradio.si:9034/;" }
};
